apiVersion: apps/v1
kind: Deployment
metadata:
  name: sir-soir-groupe2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sir-soir-groupe2
  template:
    metadata:
      labels:
        app: sir-soir-groupe2
    spec:
      containers:
        - name: groupe2
          image: sirsoir2022/sir-soir:1
          ports:
            - containerPort: 8080